no-resolv
log-queries
log-facility=/var/log/dnsmasq/dnsmasq.log
log-async=25
cache-size=10000
bogus-priv
bogus-nxdomain=64.94.110.11
rebind-domain-ok=/lan.mundix360.local/,/dmz.mundix360.local/
no-negcache
